from __future__ import annotations

from enum import Enum
from uuid import NAMESPACE_DNS, uuid5


class EntityNAMESPACE(Enum):
    ADDRESS = "ADDRESS"
    ADDRESS_TEXT_SOURCE = "ADDRESS_TEXT_SOURCE"
    CNAE = "CNAE"
    COMPANY = "COMPANY"
    COMPANY_ADDRESS = "COMPANY_ADDRESS"
    COMPANY_CNAE = "COMPANY_CNAE"
    COMPANY_COMPANY = "COMPANY_COMPANY"
    COMPANY_EMAIL = "COMPANY_EMAIL"
    COMPANY_LEGAL_PROCESS = "COMPANY_LEGAL_PROCESS"
    COMPANY_PERSON = "COMPANY_PERSON"
    COMPANY_PHONE = "COMPANY_PHONE"
    COMPANY_SANCTION = "COMPANY_SANCTION"
    COMPANY_TEXT_SOURCE = "COMPANY_TEXT_SOURCE"
    EDGE = "EDGE"
    EMAIL = "EMAIL"
    GRAPH = "GRAPH"
    LEGAL_PROCESS = "LEGAL_PROCESS"
    NODE = "NODE"
    PERSON = "PERSON"
    PERSON_ADDRESS = "PERSON_ADDRESS"
    PERSON_COMPANY = "PERSON_COMPANY"
    PERSON_EMAIL = "PERSON_EMAIL"
    PERSON_LEGAL_PROCESS = "PERSON_LEGAL_PROCESS"
    PERSON_PHONE = "PERSON_PHONE"
    PERSON_POLITICAL_EXPOSURE = "PERSON_POLITICAL_EXPOSURE"
    PERSON_SANCTION = "PERSON_SANCTION"
    PERSON_TEXT_SOURCE = "PERSON_TEXT_SOURCE"
    PHONE = "PHONE"
    POLITICAL_EXPOSURE = "POLITICAL_EXPOSURE"
    POSSIBLY_MATCHES = "POSSIBLY_MATCHES"
    SANCTION = "SANCTION"
    TEXT_SOURCE = "TEXT_SOURCE"

    def __init__(self, value: str, /) -> None:
        self.namespace = uuid5(namespace=NAMESPACE_DNS, name=value)
